name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: npm ci --legacy-peer-deps
          start: docker compose up
          wait-on: http://localhost:8080/swagger/index.html
          wait-on-timeout: 300
          browser: chrome
          config: baseUrl=http://localhost
